### ISSUE TITLE
Uncaught Error: ENOTEMPTY: directory not empty, rmdir '/tmp/atom-linter_23267K8N8aAdNg7WA'

### ISSUE THREAD

**Issue by cemsbr** [AtomLinter/linter-pylint#134]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: "Arch Linux"
**Thrown From**: [linter-pylint](https://github.com/AtomLinter/linter-pylint) package, v1.2.0

### Stack Trace

Uncaught Error: ENOTEMPTY: directory not empty, rmdir '/tmp/atom-linter_23267K8N8aAdNg7WA'

```
At fs.js:763

Error: ENOTEMPTY: directory not empty, rmdir '/tmp/atom-linter_23267K8N8aAdNg7WA'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:763:18)
    at _cleanupCallback (/home/cadu/.atom/packages/linter-pylint/node_modules/atom-linter/node_modules/tmp/lib/tmp.js:409:5)
    at /home/cadu/.atom/packages/linter-pylint/node_modules/atom-linter/lib/helpers.js:268:11
    at fs.js:1116:23
    at /usr/share/atom/resources/app.asar/node_modules/nodegit/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -0:44.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:44.5.0 editor:newline (atom-text-editor.editor.is-focused)
 10x -0:43.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:37 core:move-up (atom-text-editor.editor.is-focused)
     -0:36.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
 30x -0:36.2.0 core:delete (atom-text-editor.editor.is-focused)
     -0:31.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:31.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:30.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
 22x -0:30.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:28.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:25.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:25.4.0 core:move-left (atom-text-editor.editor.is-focused)
  9x -0:24.2.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:01.5.0 core:cut (atom-text-editor.editor.is-focused)
     -0:00.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-python",
      "python-tools",
      "linter-pep8",
      "linter-python-pyflakes",
      "linter-pydocstyle",
      "linter-pylama"
    ],
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  },
  "linter-pylint": {}
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.5.8
asciidoc-preview, v0.6.0
atom-jinja2, v0.5.0
autocomplete-python, v1.7.2
file-icons, v1.6.19
language-asciidoc, v0.12.0
language-latex, v0.6.1
linter, v1.11.4
linter-pylint, v1.2.0
minimap, v4.21.0
minimap-codeglance, v0.4.5
minimap-git-diff, v4.2.0
python-yapf, v0.10.0

# Dev
No dev packages
```

**Comment by cemsbr** [comment]
My disk was full.

**Comment by Arcanemagus** [comment]
Looks like this is a bug in the `tmp` module used for the temporary files, marking this as closed as it's not really an issue with this package.

Wow, what a coincidence @cemsbr, you posted that as I'm in the middle of typing the above :stuck_out_tongue:

Thanks for reporting back!
