### ISSUE TITLE
Problem when pickle is imported?

### ISSUE THREAD

**Issue by albireox** [AtomLinter/linter-pylint#188]
I'm getting these error when I try to lint a file

```
Error: Traceback (most recent call last): File "/usr/local/bin/pylint", line 11, in sys.exit(run_pylint()) File "/usr/local/lib/python2.7/site-packages/pylint/init.py", line 13, in run_pylint Run(sys.argv[1:]) File "/usr/local/lib/python2.7/site-packages/pylint/lint.py", line 1311, in init linter.generate_reports() File "/usr/local/lib/python2.7/site-packages/pylint/lint.py", line 985, in generate_reports config.save_results(self.stats, self.file_state.base_name) File "/usr/local/lib/python2.7/site-packages/pylint/config.py", line 78, in save_results pickle.dump(results, stream) AttributeError: 'module' object has no attribute 'dump'
```

```
Error: Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python2.7/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python2.7/site-packages/pylint/lint.py", line 1311, in __init__
    linter.generate_reports()
  File "/usr/local/lib/python2.7/site-packages/pylint/lint.py", line 985, in generate_reports
    config.save_results(self.stats, self.file_state.base_name)
  File "/usr/local/lib/python2.7/site-packages/pylint/config.py", line 78, in save_results
    pickle.dump(results, stream)
AttributeError: 'module' object has no attribute 'dump'
    at /Users/albireo/.atom/packages/linter-pylint/lib/main.js:130:19
```

As far as I can say, it happens because I'm using pickle/cPickle in that file, but I'm not sure what's the source of the problem.

**Comment by Arcanemagus** [comment]
Does this work from the CLI? Those stack traces look to be coming from `pylint` itself.

**Comment by albireox** [comment]
Actually, I figured out that this was caused because the file I was trying to lint was called `pickle.py`. That seems to be a known issue with pylint. Even after removing the file, the `.pyc` leftover file was messing up with pylint. 

So, probably it's not necessary to fix anything here, and the issue can be closed, but it would be great to catch this situation and show a more informative error message.

**Comment by Arcanemagus** [comment]
The problem is that it's not a message we are processing, but the `stderr` output of `pylint`, thanks for confirming where the problem is though!
