### ISSUE TITLE
Error in atom

### ISSUE THREAD

**Issue by drewth1** [AtomLinter/linter-pylint#226]
Hey so I don't know a ton about coding, just how to write some python code for analysis purpose. Since installing pylint along with regular linter to atom, I've had an issue of it not working. The current error is listed below. there had been a few different ones which i do not have saved. I have installed through atom and through the cmd window.   

> Error running Pylint Error: '"_program location_"' is not recognized as an internal or external command,
> operable program or batch file.
>     at Object.<anonymous> (file:///C:/Users/Drew/.atom/packages/linter-pylint/lib/main.js:161:17)
>     at Generator.next (<anonymous>)
>     at step (C:\Users\Drew\.atom\packages\linter-pylint\lib\main.js:7:273)
> 
> [Linter] Error running Pylint Error: Failed to spawn command `_program location_`. Make sure `C:\Users\Drew\OneDrive` is installed and on your PATH
>     at C:\Users\Drew\.atom\packages\linter-pylint\node_modules\atom-linter\lib\helpers.js:130:24
> (anonymous) @ C:\Users\Drew\.atom\packages\linter\lib\linter-registry.js:159

Thanks, 
Drew

**Comment by Arcanemagus** [comment]
It looks like you've tried to change the "Executable Path" setting to an invalid value. Generally this should be left at the default value (`pylint`) letting your system determine the location though the `%PATH%`. If you do need to specify a specific location it should be the _full_ path of `pylint`, in other words something like `C:\foo\bar\pylint.exe`.

**Comment by drewth1** [comment]
Alright I have fixed the pathing, however I have received the same first error. The first error occurs on files located inside a bitbucket repository, and the second error was with a file in onedrive. I am not sure if that should play a difference since those are just synced online.

**Comment by Arcanemagus** [comment]
Both of those were the same error, and that error was a misconfiguration of the "Executable Path" setting. Is there any reason you aren't just leaving that at the default?

**Comment by drewth1** [comment]
i thought maybe changing it would fix the linter, however i uninstalled and reinstalled recently so it should be set at default now

**Comment by ddaanet** [comment]
Uninstalled and reinstalling the linter-pylint package does not clear the settings saved in the `.atom/config.cson` file. You need to go to the linter-pylint package settings and clear the offending setting.

**Comment by TheEmirGroup** [comment]
Hi DDAANET
I seem to be having the same problems. I would love to use flake8 but cannot seem to even though the package is installed via ATOM from the install toolbar under File>>Settings>

ERROR IN ATOM:

**C:\Users\yusuf\.atom\packages\linter\lib\linter-registry.js:177 [Linter] Error running Flake8 Error: Failed to spawn command `C:\Users\yusuf\anaconda3\Scripts\`. Make sure `C:\Users\yusuf\anaconda3\Scripts\` is installed and on your PATH
    at C:\Users\yusuf\.atom\packages\linter-flake8\node_modules\atom-linter\lib\helpers.js:130:24
    at processTicksAndRejections (internal/process/task_queues.js:89:5)**

My config.cson file is below
![image](https://user-images.githubusercontent.com/73915817/98053402-65327080-1e30-11eb-823d-0a56068e5d06.png)

----
"*":
  core:
    telemetryConsent: "limited"
  editor:
    fontSize: 11
    tabLength: 4
    tabType: "soft"
  "exception-reporting":
    userId: "8bf0a403-0442-4cae-82e7-3324e21ab997"
  "linter-flake8":
    executablePath: "C:\\Users\\yusuf\\anaconda3\\Scripts\\"
  "linter-pylint":
    executablePath: "C:\\Users\\yusuf\\.atom\\packages\\linter-pylint"
    pythonPath: "C:\\Users\\yusuf\\.atom\\packages\\linter-pylint"
    rcFile: "C:\\Users\\yusuf\\.atom\\packages\\linter-pylint"
  "linter-ui-default":
    panelHeight: 317
----
Flake 8 is installed 
11:50 PM)where flake8
C:\Users\yusuf\anaconda3\Scripts\flake8.exe
------
echo $PATH returns the following

/c/Users/yusuf/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/yusuf/bin:/c/windows/system32:/c/windows:/c/windows/System32/Wbem:/c/windows/System32/WindowsPowerShell/v1.0:/c/windows/System32/OpenSSH:/cmd:/c/Users/yusuf/AppData/Local/Microsoft/WindowsApps:/c/Users/yusuf/AppData/Local/atom/bin:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/Users/yusuf:/c/Users/yusuf/Scripts: C/Users/yusuf/Anaconda3: C/Users/yusuf/Anaconda3/Scripts: C/Users/yusuf/anaconda3: C/Users/yusuf/anaconda3/Scripts:/c/Users/yusuf/anaconda3:/c/Users/yusuf/anaconda3/Scripts:/c/Users/yusuf:/c/Users/yusuf/Scripts: C/Users/yusuf/Anaconda3: C/Users/yusuf/Anaconda3/Scripts: /C/Users/yusuf/anaconda3: /C/Users/yusuf/anaconda3/Scripts:/c/Users/yusuf/anaconda3:/c/Users/yusuf/anaconda3/Scripts
