### ISSUE TITLE
pylint UnicodeDecodeError in write_message linting py3 source with py2 pylint

### ISSUE THREAD

**Issue by asarry** [AtomLinter/linter-pylint#233]
Hi, I installed linter-pylint yesterday but it keeps crashing, here is the log:

```
[Linter] Error running Pylint Error: Traceback (most recent call last):
  File "/usr/bin/pylint", line 3, in <module>
    run_pylint()
  File "/usr/lib/python2.7/dist-packages/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 1315, in __init__
    linter.check(args)
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 734, in check
    self._do_check(files_or_modules)
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 865, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 943, in check_astroid_module
    checker.process_tokens(tokens)
  File "/usr/lib/python2.7/dist-packages/pylint/checkers/format.py", line 797, in process_tokens
    handler(tokens, idx)
  File "/usr/lib/python2.7/dist-packages/pylint/checkers/format.py", line 604, in _check_equals_spacing
    self._check_space(tokens, i, (_MUST_NOT, _MUST_NOT))
  File "/usr/lib/python2.7/dist-packages/pylint/checkers/format.py", line 690, in _check_space
    _underline_token(token)))
  File "/usr/lib/python2.7/dist-packages/pylint/checkers/__init__.py", line 100, in add_message
    self.linter.add_message(msg_id, line, node, args, confidence)
  File "/usr/lib/python2.7/dist-packages/pylint/utils.py", line 445, in add_message
    (abspath, path, module, obj, line or 1, col_offset or 0), msg, confidence))
  File "/usr/lib/python2.7/dist-packages/pylint/reporters/text.py", line 149, in handle_message
    self.write_message(msg)
  File "/usr/lib/python2.7/dist-packages/pylint/reporters/text.py", line 139, in write_message
    self.writeln(msg.format(self._template))
  File "/usr/lib/python2.7/dist-packages/pylint/utils.py", line 120, in format
    return template.format(**dict(zip(self._fields, self)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 168: ordinal not in range(128)
    at Object.<anonymous> (main.js [sm]:134)
    at Generator.next (<anonymous>)
    at step (/home/arthur/.atom/packages/linter-pylint/lib/main.js:7)
```

I have to mention that I installed pylint before running linter-pylint, and it is located in /usr/bin/pylint. I tried to use a direct path but it doesn't work !

I hope that we'll succeed to fix this issue.

**Comment by asarry** [comment]
In fact, it works on my Python 2 projects but not on the Python 3 ones

**Comment by Arcanemagus** [comment]
If you close all Atom windows and launch it from a CLI (`atom .`) does it work?

What does `locale` output for you?

**Comment by asarry** [comment]
In fact I created some new python projects and it works well. It seems that this issue only occurs on a particular project of mine but I don't know why.
So launching it from a CLI works fine at the exception of this particular project.

Here is the `locale` output:
```
LANG=en_CA.UTF-8
LANGUAGE=
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=
```

**Comment by ddaanet** [comment]
I *guess* the issue might have to do with some of your source files containing non-ascii characters. Which python3 assume is utf-8 by default, but python2 requires an explicit encoding declaration. So I *guess* that running a python2 pylint on a non-ascii python3 file without encoding declaration could cause this crash if there is a message containing some non-ascii source code.

* Check whether the problematic source files contain non-ascii characters
* Avoid using pylint from python2 to python3
* Try fixing the files to be ascii, or provide an encoding declaration

In any case, that looks like a pylint problem that you would be able to reproduce from the terminal without Atom.

**Comment by asarry** [comment]
I took a look for any non-ascii characters on the source file but I found none of them. I also put an encoding declaration at the beginning of the file as you advised. Unfortunately, it keeps throwing an error at random moments.
I haven't mentioned it yet, but I use some external libraries like PyQt for this project and I haven't setup a virtualenv.

Thank you very much for your time.

**Comment by ddaanet** [comment]
There is a configuration setting to ignore the execution time out.

**Comment by asarry** [comment]
Thank you very much, I didn't see it when I looked on the settings.

**Comment by ddaanet** [comment]
Yay, one happy user :-)
