### ISSUE TITLE
Pylint from commandline works, atom linter-pylint does not start

### ISSUE THREAD

**Issue by colelloa** [AtomLinter/linter-pylint#238]
Hi all,
I'm having issues running pylint inside of atom, using OSX 10.13, pylint 1.8.1, Atom 1.23.1, Electron 1.6.15, Chrome 56.0.2924.87, Node 7.4.0 .

Running pylint normally from the commandline works, using something like 
`$ pylint --rcfile .pylintrc app/` 
runs and outputs successfully.

However, linter-pylint does not work in Atom. The base linter package in installed, as is pylint with normal settings (pointing to the same pylintrc file as used above, using default pylint command). I have tried using the settings to point to inside my virtual environment's pylint as well as a system-wide pylint installation, with no changes in behavior.

Looking into the dev console, I see these:
```
/Users/**/.atom/packages/linter/lib/linter-registry.js:159 
[Linter] Error running Pylint Error: Using config file /Users/**/.pylintrc
    at Object.<anonymous> (/Users/**/.atom/packages/linter-pylint/lib/main.js:161:17)
    at Generator.next (<anonymous>)
    at step (/Users/**/.atom/packages/linter-pylint/lib/main.js:7:273)
(anonymous) @ /Users/**/.atom/packages/linter/lib/linter-registry.js:159

linter-registry.js [sm]:137 
[Linter] Error running Pylint Error: Using config file /Users/**/.pylintrc
    at Object.<anonymous> (main.js [sm]:134)
    at Generator.next (<anonymous>)
    at step (/Users/**/.atom/packages/linter-pylint/lib/main.js:7)
    at process._tickCallback (internal/process/next_tick.js:103)
(anonymous) @ linter-registry.js [sm]:137
_tickCallback @ internal/process/next_tick.js:103

linter-registry.js [sm]:137 
[Linter] Error running Pylint Error: Using config file /Users/**/.pylintrc
    at Object.<anonymous> (main.js [sm]:134)
    at Generator.next (<anonymous>)
    at step (/Users/**/.atom/packages/linter-pylint/lib/main.js:7)
    at process._tickCallback (internal/process/next_tick.js:103)
(anonymous) @ linter-registry.js [sm]:137
_tickCallback @ internal/process/next_tick.js:103

linter-registry.js [sm]:137 
[Linter] Error running Pylint Error: Using config file /Users/**/.pylintrc
    at Object.<anonymous> (main.js [sm]:134)
    at Generator.next (<anonymous>)
    at step (/Users/**/.atom/packages/linter-pylint/lib/main.js:7)
    at process._tickCallback (internal/process/next_tick.js:103)
(anonymous) @ linter-registry.js [sm]:137
_tickCallback @ internal/process/next_tick.js:103

linter-registry.js [sm]:137 
[Linter] Error running Pylint Error: Using config file /Users/**/.pylintrc
    at Object.<anonymous> (main.js [sm]:134)
    at Generator.next (<anonymous>)
    at step (/Users/**/.atom/packages/linter-pylint/lib/main.js:7)
(anonymous) @ linter-registry.js [sm]:137
```

I can't figure out what these errors mean. Any ideas?

**Comment by colelloa** [comment]
i've gone as far as uninstalling atom, deleting the .atom directory, and then reinstalling everything, still, nothing works. i've generated/used other pylintrc files, to no avail.

**Comment by colelloa** [comment]
i tried installing a fork of this project - https://atom.io/packages/linter-py - and it is working. I have isolated this bug to linter-pylint

**Comment by colelloa** [comment]
upon closer look, this issue is actually the same as https://github.com/AtomLinter/linter-pylint/issues/236
