### ISSUE TITLE
Pylint won't run

### ISSUE THREAD

**Issue by dmadden1** [AtomLinter/linter-pylint#254]
Hi, 
Tried uninstall and reinstall a couple times. Still receiving the following issue: 

`C:\Users\name\.atom\packages\linter\lib\linter-registry.js:159` 
[Linter]` Error running Pylint Error: Failed to spawn command `pylint`. Make sure `pylint` is installed and on your PATH
    at C:\Users\name\.atom\packages\linter-pylint\node_modules\atom-linter\lib\helpers.js:130:24
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
(anonymous) @ `C:\Users\name\.atom\packages\linter\lib\linter-registry.js:159`

Please help.

**Comment by Arcanemagus** [comment]
Have you installed `pylint` on your computer as noted in the Readme and the error message above?
