### ISSUE TITLE
Failed to spawn command `pylint`

### ISSUE THREAD

**Issue by mmahuii** [AtomLinter/linter-pylint#303]
I'm a novice in python.
After I installed linter-pylint, when I opened atom, I encountered with this error:

[Linter] Error running Pylint Error: Failed to spawn command `pylint`. Make sure `pylint` is installed and on your PATH
    at C:\Users\MMAhuii\.atom\packages\linter-pylint\node_modules\atom-linter\lib\helpers.js:130:24
    at process._tickCallback (internal/process/next_tick.js:68:7)

Operating system: windows 10
Atom version: 1.43.0

**Comment by rajahaidar** [comment]
you need to have pylint installed on your machine/added to the path

**Comment by Seunswift** [comment]
Hi,
I am also new to programming and I was advised to install Atom for better coding experience. After installation, I installed "linter-python" package and it gave an error similar to the one above.

C:\Users\ABDULAFEEZ\.atom\packages\linter\lib\linter-registry.js:177 [Linter] Error running Pylint Error: Failed to spawn command `pylint`. Make sure `pylint` is installed and on your PATH
    at C:\Users\ABDULAFEEZ\.atom\packages\linter-pylint\node_modules\atom-linter\lib\helpers.js:130:24

I followed this instruction and installed pylint from PowerShell. Subsequently, I got this new error.

C:\Users\ABDULAFEEZ\.atom\packages\linter\lib\linter-registry.js:177 [Linter] Error running Pylint Error: Process execution timed out
    at C:\Users\ABDULAFEEZ\.atom\packages\linter-pylint\node_modules\sb-exec\lib\index.js:89:18

Thanks!

**Comment by TheEmirGroup** [comment]
Hi DDAANET
I seem to be having the same problems. I would love to use flake8 but cannot seem to even though the package is installed via ATOM from the install toolbar under File>>Settings>

ERROR IN ATOM:

C:\Users\yusuf.atom\packages\linter\lib\linter-registry.js:177 [Linter] Error running Flake8 Error: Failed to spawn command C:\Users\yusuf\anaconda3\Scripts\. Make sure C:\Users\yusuf\anaconda3\Scripts\ is installed and on your PATH
at C:\Users\yusuf.atom\packages\linter-flake8\node_modules\atom-linter\lib\helpers.js:130:24
at processTicksAndRejections (internal/process/task_queues.js:89:5)

My config.cson file is below
image

"*":
core:
telemetryConsent: "limited"
editor:
fontSize: 11
tabLength: 4
tabType: "soft"
"exception-reporting":
userId: "8bf0a403-0442-4cae-82e7-3324e21ab997"
"linter-flake8":
executablePath: "C:\Users\yusuf\anaconda3\Scripts\"
"linter-pylint":
executablePath: "C:\Users\yusuf\.atom\packages\linter-pylint"
pythonPath: "C:\Users\yusuf\.atom\packages\linter-pylint"
rcFile: "C:\Users\yusuf\.atom\packages\linter-pylint"
"linter-ui-default":
panelHeight: 317
Flake 8 is installed
11:50 PM)where flake8
C:\Users\yusuf\anaconda3\Scripts\flake8.exe
echo $PATH returns the following

/c/Users/yusuf/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/yusuf/bin:/c/windows/system32:/c/windows:/c/windows/System32/Wbem:/c/windows/System32/WindowsPowerShell/v1.0:/c/windows/System32/OpenSSH:/cmd:/c/Users/yusuf/AppData/Local/Microsoft/WindowsApps:/c/Users/yusuf/AppData/Local/atom/bin:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/Users/yusuf:/c/Users/yusuf/Scripts: C/Users/yusuf/Anaconda3: C/Users/yusuf/Anaconda3/Scripts: C/Users/yusuf/anaconda3: C/Users/yusuf/anaconda3/Scripts:/c/Users/yusuf/anaconda3:/c/Users/yusuf/anaconda3/Scripts:/c/Users/yusuf:/c/Users/yusuf/Scripts: C/Users/yusuf/Anaconda3: C/Users/yusuf/Anaconda3/Scripts: /C/Users/yusuf/anaconda3: /C/Users/yusuf/anaconda3/Scripts:/c/Users/yusuf/anaconda3:/c/Users/yusuf/anaconda3/Scripts

**Comment by TheEmirGroup** [comment]
![image](https://user-images.githubusercontent.com/73915817/98054113-0ff75e80-1e32-11eb-92a2-f723d1149e6d.png)
