### ISSUE TITLE
Flake8 and Litner8 Spawn Command in Atom even though PATH variable correctly set 

### ISSUE THREAD

**Issue by TheEmirGroup** [AtomLinter/linter-pylint#317]
![image](https://user-images.githubusercontent.com/73915817/98054141-1dace400-1e32-11eb-954f-0e51a590bcd2.png)

I seem to be having problems with Flake8 and Linter.  I have tried many things, the PATH variable is correctly set and the command _where flake 8 returns the path to the executable which is in my $PATH has also been set correctly as the printouts will show.

I would love to use flake8 but cannot seem to even though the package is installed via ATOM from the install toolbar under File>>Settings>but cannot seem to get past the SPAWN Command issues and as a result Linter fails to installs when I open a .py file.

Please can someone in dummy speak help me sort this out to improve my coding capabilities in ATOM

ERROR IN ATOM:

C:\Users\yusuf.atom\packages\linter\lib\linter-registry.js:177 [Linter] Error running Flake8 Error: Failed to spawn command C:\Users\yusuf\anaconda3\Scripts\. Make sure C:\Users\yusuf\anaconda3\Scripts\ is installed and on your PATH
at C:\Users\yusuf.atom\packages\linter-flake8\node_modules\atom-linter\lib\helpers.js:130:24
at processTicksAndRejections (internal/process/task_queues.js:89:5)

"*":
core:
telemetryConsent: "limited"
editor:
fontSize: 11
tabLength: 4
tabType: "soft"
"exception-reporting":
userId: "8bf0a403-0442-4cae-82e7-3324e21ab997"
"linter-flake8":
executablePath: "C:\Users\yusuf\anaconda3\Scripts\"
"linter-pylint":
executablePath: "C:\Users\yusuf\.atom\packages\linter-pylint"
pythonPath: "C:\Users\yusuf\.atom\packages\linter-pylint"
rcFile: "C:\Users\yusuf\.atom\packages\linter-pylint"
"linter-ui-default":
panelHeight: 317

--------
Flake 8 is installed
11:50 PM)where flake8
C:\Users\yusuf\anaconda3\Scripts\flake8.exe
---------

echo $PATH

/c/Users/yusuf/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/yusuf/bin:/c/windows/system32:/c/windows:/c/windows/System32/Wbem:/c/windows/System32/WindowsPowerShell/v1.0:/c/windows/System32/OpenSSH:/cmd:/c/Users/yusuf/AppData/Local/Microsoft/WindowsApps:/c/Users/yusuf/AppData/Local/atom/bin:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/Users/yusuf:/c/Users/yusuf/Scripts: C/Users/yusuf/Anaconda3: C/Users/yusuf/Anaconda3/Scripts: C/Users/yusuf/anaconda3: C/Users/yusuf/anaconda3/Scripts:/c/Users/yusuf/anaconda3:/c/Users/yusuf/anaconda3/Scripts:/c/Users/yusuf:/c/Users/yusuf/Scripts: C/Users/yusuf/Anaconda3: C/Users/yusuf/Anaconda3/Scripts: /C/Users/yusuf/anaconda3: /C/Users/yusuf/anaconda3/Scripts:/c/Users/yusuf/anaconda3:/c/Users/yusuf/anaconda3/Scripts

**Comment by TheEmirGroup** [comment]
Additionally when I try to do type this
12:23 AMpip install flake8
bash: /c/Users/yusuf/AppData/Local/Microsoft/WindowsApps/pip: Permission denied

I am not sure if this means that I don't have flake8 installed.  As you can see I am using Windows. I have also installed Litner-Flake8 via the install GUI inside ATOM
