### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by bista-bhavesh** [AtomLinter/linter-pylint#65]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Ubuntu 14.04.3
**Thrown From**: [linter-pylint](https://github.com/AtomLinter/linter-pylint) package, v1.0.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At /usr/share/atom/resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
  at /home/bista/.atom/packages/linter-pylint/node_modules/atom-linter/lib/helpers.coffee:45:30
  at Object.module.exports.Helpers._exec (/home/bista/.atom/packages/linter-pylint/node_modules/atom-linter/lib/helpers.coffee:25:16)
  at Object.module.exports.Helpers.exec (/home/bista/.atom/packages/linter-pylint/node_modules/atom-linter/lib/helpers.coffee:16:13)
  at /home/bista/.atom/packages/linter-pylint/lib/main.coffee:80:26
  at /home/bista/.atom/packages/linter-pylint/node_modules/atom-linter/lib/helpers.coffee:141:23
  at /home/bista/.atom/packages/linter-pylint/node_modules/atom-linter/lib/helpers.coffee:140:17
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:19.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:15.8.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:15.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:15.6.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:09.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:01.8.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "monokai"
    ]
  },
  "linter-pylint": {
    "executable": "/usr/local/bin"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
atom-material-ui, v0.6.0
auto-indent, v0.5.0
autocomplete-python, v0.5.3
autosave-plus, v0.5.2
css-snippets, v0.8.0
file-icons, v1.6.9
git-diff-details, v0.20.0
git-go, v1.0.1
git-log, v0.4.1
highlight-line, v0.11.0
linter, v1.5.0
linter-flake8, v1.6.1
linter-pep8, v1.0.1
linter-pyflakes, v0.0.5
linter-pylint, v1.0.0
linter-python-pep8, v0.2.0
linter-python-pyflakes, v0.1.0
minimap, v4.13.2
minimap-color-highlight, v4.1.4
minimap-highlight-selected, v4.3.0
monokai, v0.18.0
odoo-snippets, v0.1.0
pigments, v0.13.2
project-manager, v2.4.0
python-autopep8, v0.1.3
python-iresolve, v0.0.3
python-tools, v0.3.0
remote-edit, v1.8.18
travis-ci-status, v0.18.0
tree-view-git-branch, v0.0.2
tree-view-git-status, v0.2.0

# Dev
No dev packages
```

**Comment by SpainTrain** [comment]
> "executable": "/usr/local/bin"

Your `pylint` executable appears to be set to a directory.  In the config for `linter-pylint` you will want to set `executable` to "`pylint`" or the absolute path to your installed `pylint`.

**Comment by steelbrain** [comment]
@SpainTrain That's 100% true.
Closing based on comment above.
