### ISSUE TITLE
Failed to load the linter-pylint package

### ISSUE THREAD

**Issue by benjavides** [AtomLinter/linter-pylint#70]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [linter-pylint](https://github.com/AtomLinter/linter-pylint) package, v1.0.0

### Stack Trace

Failed to load the linter-pylint package

```
At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Benjamín\.atom\packages\linter-pylint\lib\main.coffee:2:11)
  at Object.<anonymous> (C:\Users\Benjamín\.atom\packages\linter-pylint\lib\main.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:761:34)
  at C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:192:28
  at Package.module.exports.Package.measure (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.load (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:183:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:369:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\atom.js:667:21)
  at Object.<anonymous> (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\Benjamín\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///C:/Users/Benjam%C3%ADn/AppData/Local/atom/app-1.0.19/resources/app.asar/static/index.js:82:25)
  at window.onload (file:///C:/Users/Benjam%C3%ADn/AppData/Local/atom/app-1.0.19/resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v0.5.4
linter, v1.6.0
linter-flake8, v1.6.1
linter-pep8, v1.0.1
linter-pylint, v1.0.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
See @Arcanemagus 's commet here https://github.com/AtomLinter/linter-flake8/issues/82#issuecomment-143593306

**Comment by benjavides** [comment]
I ran this commands to install a set of packages:

> pip install --upgrade pylint pep8 flake8
  apm install linter linter-pylint linter-pep8 linter-flake8
  apm install script
  apm install autocomplete-python
  pip install --upgrade autopep8
  apm install atom-beautify

**Comment by steelbrain** [comment]
that is super-super weird.
On a side note, you can batch apm install commands like
```
apm install atom-beautify linter linter-flake8 linter-pep8 linter-pylint autocomplete-python script
```
and does this help?
```
mv ~/.atom ~/.atom-backup
apm install linter linter-flake8 linter-pep8 linter-pylint
```
