### ISSUE TITLE
Failed to activate the linter-pylint package

### ISSUE THREAD

**Issue by jaredjburgess** [AtomLinter/linter-pylint#90]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: [linter-pylint](https://github.com/AtomLinter/linter-pylint) package, v1.0.4

### Stack Trace

Failed to activate the linter-pylint package

```
At require(...)(...)[1].getFileName is not a function

TypeError: require(...)(...)[1].getFileName is not a function
    at Object.install (/Users/jaredburgess/.atom/packages/linter-pylint/node_modules/atom-package-deps/lib/main.js:15:47)
    at Object.module.exports.activate (/Users/jaredburgess/.atom/packages/linter-pylint/lib/main.coffee:30:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "ignoredNames": [
      ".pyc",
      "*.DS_Store",
      "*.git",
      "env"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.5
atom-material-ui, v0.8.0
file-icons, v1.6.12
linter, v1.11.2
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-pylint, v1.0.4
minimap, v4.16.1
pigments, v0.19.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Fixed by https://github.com/steelbrain/package-deps/pull/31

Here's what you can do to make it work on your installation
```
cd ~/.atom/packages/linter-pylint
rm -rf node_modules/atom-package-deps
npm install atom-package-deps@latest
```

**Comment by jaredjburgess** [comment]
Ah Thanks!

**Comment by mgracer48** [comment]
doesnt work

**Comment by Arcanemagus** [comment]
@mgracer48 Can you please file a new issue with the stack trace you are getting? Also make sure you are on v2.0.1 as there was a bug in v2.0.0.
